steps:
    - imports:
          align: none
          list_align: with_module_name
          pad_module_names: false
          long_list_align: new_line_multiline
          empty_list_align: inherit
          list_padding: 4
          separate_lists: false
          space_surround: true
          post_qualify: true
    - language_pragmas:
          style: vertical
          align: true
          remove_redundant: true
    - simple_align:
          cases: true
          top_level_patterns: true
          records: true
    - trailing_whitespace: {}
